#!/bin/sh

youtube-dl --format bestaudio/flac/best \
    -x --audio-format flac --audio-quality 0 --add-metadata \
    -o "%(track)s@%(title)s@%(artist)s@%(creator)s@%(channel)s@%(uploader)s.%(ext)s" \
    --exec "python3 postdl.py {}" \
    "$@"
